### PR TITLE
I have corrected you readmie file

### PR DESCRIPTION
**Pull request by mohdammar128**
I Have done some Modification in your readMe.md file

### CODE REVIEW

**Comment by mohdammar128** [comment]
can you tell me what are the tech stacks you have used

**Comment by siddharthO3** [comment]
> can you tell me what are the tech stacks you have used

I have used Kotlin and Jetpack Compose for this project

**Review by siddharthO3 — APPROVED** [review]
All ok

**Comment by mohdammar128** [comment]
> 

So what do you think , i mean Do you further expand of this project

**Pull request merged**
